PHP 8.1: Added `enum` support to valid sniffs
squizlabs/PHP_CodeSniffer pull request #3482
Opened 2021-11-20 18:35 UTC by kukulich

2022-01-17 08:05 UTC, kukulich commented
Rebased on master and ready for review.

2022-01-17 21:57 UTC, gsherwood commented
First, this is terrific. Thank you.

Curious as to any opinions on treating enums with the exact same sniff rules as classes, especially PSR2 and PSR12 standards.

I'm in 2 minds. Given they are basically classes, treating them in the same way makes sense to me. But the PSR standards obviously don't mention enums, so it's quite possible someone reports a bug that PHPCS is enforcing rules that are not stated in the PSR.

I think there is an argument to say they are implied in the PSR, given the line :
> The term "class" refers to all classes, interfaces, and traits.

and the contents of the RFC itself:
> Enumerations are built on top of classes and objects. That means, except where otherwise noted, “how would Enums behave in situation X” can be answered “the same as any other object instance.”

But keen for other opinons.

2022-01-17 22:37 UTC, jrfnl commented
Just my two cents:
Treating enums like classes in every single way but the "signature" (which would need special handling) and the "case" statements (which should probably be treated similar to class constants), is the logical thing to do and is how I would expect sniffs to behave.

FYI: I'm hoping to review most of the work in this PR tomorrow (if still needed by then).

2022-01-17 22:42 UTC, gsherwood requested changes

2022-01-17 22:47 UTC, kukulich commented on src/Standards/Squiz/Tests/PHP/NonExecutableCodeUnitTest.2.inc
> +trait Something {
Fixed.

2022-01-17 22:56 UTC, gsherwood approved these changes

2022-01-18 16:15 UTC, jrfnl commented
@kukulich I've started reviewing - shall I pull a PR with various tweaks to your branch to get through the small stuff ?

2022-01-18 16:16 UTC, kukulich commented
@jrfnl Feel free :)

2022-01-18 22:52 UTC, jrfnl commented
PR https://github.com/kukulich/PHP_CodeSniffer/pull/1 has been pulled with some small improvements.

> Notes:
> * Most are just small test improvements to add additional safeguards.
> * The new test in `Squiz.Commenting.InlineComment` was breaking a test which had to be at the end of the file. Fixed by moving the new test up.
> * The new test in `Squiz.WhiteSpace.ControlStructureSpacing` wasn't actually testing anything. Fixed by wrapping it in a control structure.
> * The test improvements involving "valid name" sniffs will, in most cases, now cause the tests to fail. This is due to bug https://github.com/squizlabs/PHP_CodeSniffer/pull/3534, which was discovered during this review. The tests will pass once the upstream bugfix PR has been merged.
> * The `Squiz.Classes.ValidClassName` sniff needed an additional fix to be able to handle backed enums.

That concludes part 1 of the review (= review current fixes).

For part 2, I'm now going to look at an additional set of results from token searches to see if any of the additional sniffs flagged need tests/sniff fixes for enum support.

2022-01-19 02:04 UTC, jrfnl commented
Not 100% done yet, but here are my preliminary findings:

Additional sniffs for which tests/support should be added (I've prepared the commits for a few already):
- [x] `PEAR.WhiteSpace.ScopeClosingBrace` - Needs tests.
- [x] `PSR12.Classes.OpeningBraceSpace` - Needs tests.
- [x] `Squiz.Commenting.ClosingDeclarationComment` - Needs support + tests
- [x] `Squiz.Commenting.DocCommentAlignment` - Needs support + tests. Probably will also need adjustment to support docblocks for enum cases.
- [x] `Squiz.WhiteSpace.ScopeClosingBrace` - Needs tests.
- [ ] `File::getMemberProperties()` - Should this get an exception for enums, along the same lines as for interfaces ?
- [ ] `File::findImplementedInterfaceNames()` - Should support finding the interfaces implemented by enums too
- [ ] `File::findEndOfStatement()` - Needs tests.
- [ ] `Generic.CodeAnalysis.UnnecessaryFinalModifier` - enums are final by design, so while the `final` modifier for methods is allowed, it is always unnecessary.
- [ ] `Generic.CodeAnalysis.UnusedFunctionParameter` - Needs tests, may also need to take enums implementing interfaces into account
- [ ] `Generic.Formatting.MultipleStatementAlignment` - Needs tests, also for case statements (once support has been added for those)
- [ ] `Generic.WhiteSpace.ScopeIndent` - Needs tests.
- [ ] `PSR12.Files.FileHeader` - Needs tests.
- [ ] `Squiz.Classes.SelfMemberReference` - Should actually probably support all OO tokens. Needs tests for all to be added.
- [ ] `Squiz.Commenting.ClassComment` - Should actually probably support all OO tokens. Needs tests for all to be added. Also take note of inconsistency with PEAR version of this sniff (which has previously already been adjusted to support all OO tokens).

Note sure about the `Squiz.Classes.ClassDeclaration` sniff. What do you think ?

2022-02-14 22:41 UTC, kukulich commented
Rebased and green.

2022-02-22 13:54 UTC, jaroslavlibal commented
I'm not sure if this is the right place to mention this, so apologies if not.

If I have an enum with some methods, like this:

```php
<?php declare(strict_types = 1);

namespace Model\Language;

enum Language: string
{

    case CS = 'cs';
    case EN = 'en';

    /** @return string[] */
        private static function getNames(): array
        {
            return [
            self::CS->value => 'cs_CZ',
            self::EN->value => 'en_US',
            ];
        }
}
```

Then firstly `phpcbf` breaks the formatting (in the example, the output after it has been "fixed") and secondly `phpcs` reports a problem on the sniff `PSR1.Files.SideEffects.FoundWithSymbols`.

> A file should declare new symbols (classes, functions, constants, etc.) and cause no other side effects, or it should execute logic with side effects, but should not do both.

2022-03-02 11:08 UTC, faytekin approved these changes

2022-03-15 09:10 UTC, rrajkomar commented
Hello, 
Is there any ETA for this merge ? Currently php enums are unusable with PHPCS with is delaying any migration to PHP8.1 with Enums (at least without disabling analysis on those files).
Also is there any estimation on the 3.7.0 release date ?
Thanks.

2022-03-15 09:11 UTC, rrajkomar commented
Hello, 
Is there any ETA for this merge ? Currently php enums are unusable with PHPCS with is delaying any migration to PHP8.1 with Enums (at least without disabling analysis on those files).
Also is there any estimation on the 3.7.0 release date ?
Thanks.

2022-03-15 09:17 UTC, gsherwood commented
> Hello, Is there any ETA for this merge ? Also is there any estimation on the 3.7.0 release date ?
There is no ETA. I've been exceptionally busy and haven't been able to review the changes since I last approved.

2022-03-18 03:38 UTC, gsherwood commented
@jrfnl @kukulich I'm keen to get a release out with at least some ENUM support.

I think what's here already is great. While more support could be added, I'd like to know if either of you see any blockers to getting this merged in. I know I'm not going to have time to work on any of the additional sniff changes, but I can at least get this merged and released to partial support is available.

2022-03-18 05:42 UTC, kukulich commented
I would be happy with release with partial enum support :)

2022-03-18 09:39 UTC, jrfnl commented
> @jrfnl @kukulich I'm keen to get a release out with at least some ENUM support.
> 
> I think what's here already is great. While more support could be added, I'd like to know if either of you see any blockers to getting this merged in. I know I'm not going to have time to work on any of the additional sniff changes, but I can at least get this merged and released to partial support is available.

Happy for this to be merged.

I could pull the extra changes which I worked on already either to this PR or separately, whichever is preferred.

Not all sniffs having support is IMO not a blocker for the release.

However, I do think it would be good if the below three from my previous comment got sorted before the release:

> - [ ] `File::getMemberProperties()` - Should this get an exception for enums, along the same lines as for interfaces ?
> - [ ] `File::findImplementedInterfaceNames()` - Should support finding the interfaces implemented by enums too
> - [ ] `File::findEndOfStatement()` - Needs tests.

* For the first I'd like a second opinion before actioning this.
* I can work on getting the second sorted.
* Anyone else up for looking at the third ?

Other than that for a release to go out, please be aware that IMO supporting intersection types will require the introduction of a new token (similar to what was done for union types), so that would mean that support for intersection types would need to wait until `3.8.0`.

2022-03-21 14:46 UTC, janedbal commented
> Happy for this to be merged.

Great! We are really looking forward to this! Can we expect new version this week?

2022-03-23 21:11 UTC, acidjazz commented
Almost 5 months since the release of PHP 8.1 Enums - lets merge and release!

2022-03-31 22:27 UTC, merged

2022-03-31 22:30 UTC, gsherwood commented
This is now merged. Thanks all.