fix(docs): change filter arguments to match PascalCase
squizlabs/PHP_CodeSniffer pull request #3879
Opened 2023-08-21 10:40 UTC by simonsan

## Description
It fixes documentation of the command-line interface for the `filter` command.

### Suggested changelog entry
`Change documentation of filter command to match internally used PascalCase`

### Related issues/external references

Fixes #3877 

## Types of changes
- [x] Bug fix _(non-breaking change which fixes an issue)_
- [ ] New feature _(non-breaking change which adds functionality)_
- [ ] Breaking change _(fix or feature that would cause existing functionality to change)_
    - [ ] This change is only breaking for integrators, not for external standards or end-users.
- [x] Documentation improvement

## PR checklist

- [x] I have checked there is no other PR open for the same change.
- [ ] I have read the [Contribution Guidelines](.github/CONTRIBUTING.md).
- [x] I grant the project the right to include and distribute the code under the BSD-3-Clause license (and I have the right to grant these rights).
- [ ] I have added tests to cover my changes.
- [ ] I have verified that the code complies with the projects coding standards.

2023-08-21 21:33 UTC, jrfnl requested changes
Thanks for the PR @simonsan! Could you also make the same change on line 1406 (same file) ?

2023-08-22 06:00 UTC, jrfnl approved these changes
Thank you @simonsan !

The changelog normally contains the full name of the contributor. Would you mind sharing yours ?

2023-08-25 14:50 UTC, DannyvdSluijs approved these changes

2023-08-27 15:07 UTC, jrfnl commented
> Hey there, yes, as a privacy activist I wouldn't share my full name on the internet. I grant the project the right to include and distribute the code under the BSD-3-Clause license (and I have the right to grant these rights). 👍🏽

Thanks for letting me know @simonsan and I fully respect that. I'll just credit you by your GitHub handle in that case) presuming that's okay ?).

2023-08-27 15:24 UTC, merged

2023-12-08 23:03 UTC, jrfnl commented
FYI: this fix is included in today's [PHP_CodeSniffer 3.8.0 release](https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.8.0).

As per #3932, development on PHP_CodeSniffer will continue in the [PHPCSStandards/PHP_CodeSniffer](https://github.com/PHPCSStandards/PHP_CodeSniffer) repository. If you want to stay informed, you may want to start "watching" that repo (or watching releases from that repo).